apiVersion: llmd.ai/v1alpha1
kind: VariantAutoscaling
metadata:
  name: qwen-32b-model-b
  labels:
    inference.optimization/acceleratorName: "H100"
    llm-d.ai/model: "Qwen3-32B"
    llm-d.ai/inference-serving: "true"
    llm-d.ai/guide: "multi-inferencepool"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qwen-32b-model-b
  modelID: "Qwen/Qwen3-32B"
  minReplicas: 1
  maxReplicas: 8
  variantCost: "10.0"
