apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../vllm
namePrefix: eight-gpu-
labels:
  - pairs:
      llm-d.ai/model: DeepSeek-R1-Distill-Llama-70B
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-profile.yaml
