router:
  inferencePool:
    failureMode: FailOpen

  epp:
    pluginsConfigFile: "multi-endpoint.yaml"
    pluginsCustomConfig:
      multi-endpoint.yaml: |
        apiVersion: llm-d.ai/v1
        kind: EndpointPickerConfig
        plugins:
        - type: queue-scorer
        - type: max-score-picker
        schedulingProfiles:
        - name: default
          plugins:
          - pluginRef: queue-scorer
          - pluginRef: max-score-picker

  modelServers:
    matchLabels:
      llm-d.ai/guide: "diffusion-serving-multi-endpoint"
    protocol: http
