apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-epp-prometheus
  labels:
    app.kubernetes.io/name: keda-epp-prometheus
    app.kubernetes.io/component: thanos-auth
    app.kubernetes.io/managed-by: kustomize
