apiVersion: v1
kind: Secret
metadata:
  name: keda-prometheus-auth
  labels:
    app.kubernetes.io/name: keda-epp-prometheus
    app.kubernetes.io/component: thanos-auth
    app.kubernetes.io/managed-by: kustomize
  annotations:
    kubernetes.io/service-account.name: keda-epp-prometheus
type: kubernetes.io/service-account-token
