apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: REPLACE_MODEL_SERVER_IMAGE
    newName: ghcr.io/project-hami/vllm-metax
    newTag: 0.24.0-maca.ai3.8.2.5-torch2.10-py310-ubuntu22.04-amd64
