apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../recipes/modelserver/base/single-host/default

namePrefix: optimized-baseline-mthreads-sglang-

components:
  - ../../../../recipes/modelserver/components/images/mthreads-sglang/release

labels:
  - pairs:
      llm-d.ai/guide: optimized-baseline
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: mthreads
      llm-d.ai/engine-type: sglang
      llm-d.ai/model: DeepSeek-V4-Flash-0731-FP8-mt
    includeSelectors: true
    includeTemplates: true

patches:
  - path: patch-sglang.yaml
