apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: modelserver
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen3-14B"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8200"
            - "--served-model-name"
            - "Qwen/Qwen3-14B"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
            - "--tensor-parallel-size=1"
            - "--max-num-batched-tokens=8192"
            - "--gpu-memory-utilization=0.55"
            - "--kv-transfer-config"
            - '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VLLM_NIXL_SIDE_CHANNEL_PORT
              value: "5600"
            - name: VLLM_HTTP_TIMEOUT_KEEP_ALIVE
              value: "120"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
            seccompProfile:
              type: Unconfined
          resources:
            limits:
              memory: 64Gi
              metax-tech.com/gpu: "1"
            requests:
              cpu: "4"
              memory: 16Gi
              metax-tech.com/gpu: "1"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 180
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 100Gi
        - name: torch-compile-cache
          emptyDir: {}
