apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-d-kv-cache-storage # If you change this, update the ./manifests/vllm patches accordingly.
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 9000Gi
  # Uncomment the following line to specify a storage class for the PVC. If you leave it commented out, the default storage class will be used.
  # storageClassName: "" 