apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-d-wva-bbnv31
resources:
  - ../../../../../../llm-d-workload-variant-autoscaler/config/default
  - ../../../../../guides/workload-autoscaling/wva-config/base/controller-manager-token-secret.yaml
patches:
  - path: ../../../../../guides/workload-autoscaling/wva-config/base/controller-deployment-patch.yaml
    target:
      kind: Deployment
      name: workload-variant-autoscaler-controller-manager
  - path: ../../../../../guides/workload-autoscaling/wva-config/base/servicemonitor-patch.yaml
    target:
      kind: ServiceMonitor
      name: workload-variant-autoscaler-controller-manager-metrics-monitor
  - path: ../../../../../guides/workload-autoscaling/wva-config/base/metrics-auth-rolebinding-patch.yaml
    target:
      kind: ClusterRoleBinding
      name: workload-variant-autoscaler-prometheus-metrics-auth-rolebinding
  - path: ../../../../../guides/workload-autoscaling/wva-config/base/epp-token-secret-patch.yaml
    target:
      kind: Secret
      name: workload-variant-autoscaler-epp-metrics-token
  - path: ../../../../../guides/workload-autoscaling/wva-config/platform/ocp/configmap-patch.yaml
    target:
      kind: ConfigMap
      name: workload-variant-autoscaler-wva-variantautoscaling-config
  - path: ../../../../../guides/workload-autoscaling/wva-config/platform/ocp/servicemonitor-label-patch.yaml
    target:
      kind: ServiceMonitor
      name: workload-variant-autoscaler-controller-manager-metrics-monitor
images:
  - name: controller
    newName: ghcr.io/llm-d/llm-d-workload-variant-autoscaler
    newTag: dev-7e45c529
