apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm
  labels:
    llm-d.ai/role: both
spec:
  selector:
    matchLabels:
      llm-d.ai/role: both
  podMetricsEndpoints:
    - port: "8000"
      path: /metrics
      interval: 15s
