apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: intel-decode-claim-template
spec:
  spec:
    devices:
      requests:
        - name: rdma-net-interface
          exactly:
            deviceClassName: rdma-dranet
            count: 1
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: intel-prefill-claim-template
spec:
  spec:
    devices:
      requests:
        - name: rdma-net-interface
          exactly:
            deviceClassName: rdma-dranet
            count: 1
