#
# AMD-CI test setup
#

apiVersion: disaggregatedset.x-k8s.io/v1
kind: DisaggregatedSet
metadata:
  name: pd-disagg
spec:
  roles:
    - name: prefill
      spec:
        leaderWorkerTemplate:
          workerTemplate:
            metadata:
              annotations:
                k8s.v1.cni.cncf.io/networks: |
                  [
                    {"name":"amd-host-device-nad","namespace":"default","interface":"net1"},
                    {"name":"amd-host-device-nad","namespace":"default","interface":"net2"}
                  ]
            spec:
              containers:
                - name: modelserver
                  imagePullPolicy: Always
                  resources:
                    limits:
                      amd.com/gpu: "2"
                      amd.com/vnic: "2"
                    requests:
                      amd.com/gpu: "2"
                      amd.com/vnic: "2"
                  env:
                    # Prefer DMABUF on this cluster (optional, but avoids warnings when peermem is not available)
                    - name: MORI_ENABLE_DMABUF_REG
                      value: "1"
                    - name: MORI_IB_GID_INDEX
                      value: "1"
    - name: decode
      spec:
        leaderWorkerTemplate:
          workerTemplate:
            metadata:
              annotations:
                k8s.v1.cni.cncf.io/networks: |
                  [
                    {"name":"amd-host-device-nad","namespace":"default","interface":"net1"},
                    {"name":"amd-host-device-nad","namespace":"default","interface":"net2"}
                  ]
            spec:
              containers:
                - name: modelserver
                  imagePullPolicy: Always
                  resources:
                    limits:
                      amd.com/gpu: "2"
                      amd.com/vnic: "2"
                    requests:
                      amd.com/gpu: "2"
                      amd.com/vnic: "2"
                  env:
                    # Prefer DMABUF on this cluster (optional, but avoids warnings when peermem is not available)
                    - name: MORI_ENABLE_DMABUF_REG
                      value: "1"
                    - name: MORI_IB_GID_INDEX
                      value: "1"
