apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../tpu/v7/vllm/gke
components:
  - ../../../../../../../recipes/observability/tracing/components/vllm-deployment
