apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: optimized-baseline-nvidia-gpu-vllm-decode
spec:
  metrics:
    - type: External
      external:
        metric:
          name: wva_desired_replicas
          selector:
            matchLabels:
              variant_name: optimized-baseline-nvidia-gpu-vllm-decode
              exported_namespace: llm-d-wva-yottnm
        target:
          type: AverageValue
          averageValue: "1"
