apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

patchesJson6902:
  - target:
      group: keda.sh
      version: v1alpha1
      kind: ScaledObject
      name: optimized-baseline-nvidia-gpu-vllm-decode-saturation
    patch: scaledobject-patch.yaml
