{
 "title": "baseline-compare-llm-d",
 "description": "Compare baseline vLLM with llm-d deployments",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "model_name",
    "label": "model_name",
    "query": {
     "query": "label_values(vllm:generation_tokens_total,model_name)"
    }
   },
   { "name": "baseline", "label": "baseline", "query": { "query": "label_values(namespace)" } },
   { "name": "llm_d", "label": "llm_d", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P99 (baseline)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P95 (baseline)"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P90 (baseline)"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P50 (baseline)"
    },
    {
     "expr": "avg(rate(vllm:e2e_request_latency_seconds_sum{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "Average (baseline)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P99 (llm_d)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P95 (llm_d)"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P90 (llm_d)"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P50 (llm_d)"
    },
    {
     "expr": "avg(rate(vllm:e2e_request_latency_seconds_sum{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "Average (llm_d)"
    }
   ]
  },
  {
   "title": "Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(vllm:prompt_tokens_total{namespace=\"$baseline\",model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "Prompt Tokens/Sec (baseline)"
    },
    {
     "expr": "sum(rate(vllm:generation_tokens_total{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "Generation Tokens/Sec (baseline)"
    },
    {
     "expr": "sum(rate(vllm:prompt_tokens_total{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "Prompt Tokens/Sec (llm_d)"
    },
    {
     "expr": "sum(rate(vllm:generation_tokens_total{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "Generation Tokens/Sec (llm_d)"
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Inter token latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P99 (baseline)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P95 (baseline)"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P90 (baseline)"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P50 (baseline)"
    },
    {
     "expr": "avg(rate(vllm:time_per_output_token_seconds_sum{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])\n/\nrate(vllm:time_per_output_token_seconds_count{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "Mean (baseline)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P99 (llm_d)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P95 (llm_d)"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P90 (llm_d)"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P50 (llm_d)"
    },
    {
     "expr": "avg(rate(vllm:time_per_output_token_seconds_sum{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])\n/\nrate(vllm:time_per_output_token_seconds_count{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "Mean (llm_d)"
    }
   ]
  },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(vllm:num_requests_running{model_name=\"$model_name\",namespace=\"$baseline\"})",
     "legendFormat": "Num Running (baseline)"
    },
    {
     "expr": "sum(vllm:num_requests_swapped{model_name=\"$model_name\",namespace=\"$baseline\"})",
     "legendFormat": "Num Swapped (baseline)"
    },
    {
     "expr": "sum(vllm:num_requests_waiting{model_name=\"$model_name\",namespace=\"$baseline\"})",
     "legendFormat": "Num Waiting (baseline)"
    },
    {
     "expr": "sum(vllm:num_requests_running{model_name=\"$model_name\",namespace=\"$llm_d\"})",
     "legendFormat": "Num Running (llm_d)"
    },
    {
     "expr": "sum(vllm:num_requests_swapped{model_name=\"$model_name\",namespace=\"$llm_d\"})",
     "legendFormat": "Num Swapped (llm_d)"
    },
    {
     "expr": "sum(vllm:num_requests_waiting{model_name=\"$model_name\",namespace=\"$llm_d\"})",
     "legendFormat": "Num Waiting (llm_d)"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P99 (baseline)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P95 (baseline)"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P90 (baseline)"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])))",
     "legendFormat": "P50 (baseline)"
    },
    {
     "expr": "avg(rate(vllm:time_to_first_token_seconds_sum{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "Average (baseline)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P99 (llm_d)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P95 (llm_d)"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P90 (llm_d)"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])))",
     "legendFormat": "P50 (llm_d)"
    },
    {
     "expr": "avg(rate(vllm:time_to_first_token_seconds_sum{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "Average (llm_d)"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(vllm:gpu_cache_usage_perc{model_name=\"$model_name\",namespace=\"$baseline\"})",
     "legendFormat": "GPU Cache Usage (baseline)"
    },
    {
     "expr": "sum(vllm:cpu_cache_usage_perc{model_name=\"$model_name\",namespace=\"$baseline\"})",
     "legendFormat": "CPU Cache Usage (baseline)"
    },
    {
     "expr": "sum(vllm:gpu_cache_usage_perc{model_name=\"$model_name\",namespace=\"$llm_d\"})",
     "legendFormat": "GPU Cache Usage (llm_d)"
    },
    {
     "expr": "sum(vllm:cpu_cache_usage_perc{model_name=\"$model_name\",namespace=\"$llm_d\"})",
     "legendFormat": "CPU Cache Usage (llm_d)"
    }
   ]
  },
  {
   "title": "Request Prompt Length (baseline)",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Prompt Length (llm_d)",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Generation Length (baseline)",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generation Length (llm_d)",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "baseline ({{finished_reason}})"
    },
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "llm_d ({{finished_reason}})"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "avg(rate(vllm:request_queue_time_seconds_sum{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "Baseline"
    },
    {
     "expr": "avg(rate(vllm:request_queue_time_seconds_sum{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "llm-d"
    }
   ]
  },
  {
   "title": "Requests Prefill and Decode Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "avg(rate(vllm:request_prefill_time_seconds_sum{model_name=\"$model_name\",namespace=\"$llm_d\"}[30m]))",
     "legendFormat": "Prefill (llm_d)"
    },
    {
     "expr": "avg(rate(vllm:request_decode_time_seconds_sum{model_name=\"$model_name\",namespace=\"$llm_d\"}[30m]))",
     "legendFormat": "Decode (llm_d)"
    },
    {
     "expr": "avg(rate(vllm:request_prefill_time_seconds_sum{model_name=\"$model_name\",namespace=\"$baseline\"}[30m]))",
     "legendFormat": "Prefill (Baseline)"
    },
    {
     "expr": "avg(rate(vllm:request_decode_time_seconds_sum{model_name=\"$model_name\",namespace=\"$baseline\"}[30m]))",
     "legendFormat": "Decode (Baseline)"
    }
   ]
  },
  {
   "title": "Max Generation Token in Sequence Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(vllm:request_max_num_generation_tokens_sum{model_name=\"$model_name\",namespace=\"$baseline\"}[$__rate_interval]))",
     "legendFormat": "Tokens (baseline)"
    },
    {
     "expr": "sum(rate(vllm:request_max_num_generation_tokens_sum{model_name=\"$model_name\",namespace=\"$llm_d\"}[$__rate_interval]))",
     "legendFormat": "Tokens (llm_d)"
    }
   ]
  }
 ]
}