apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: xpu-qwen3-235b-claim
  labels:
    llm-d.ai/model: Qwen3-235B-A22B
spec:
  spec:
    devices:
      requests:
        - name: intel
          exactly:
            deviceClassName: gpu.intel.com
            count: 8
        - name: nic
          exactly:
            deviceClassName: dranet-rdma
            count: 1
