apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../recipes/modelserver/base/single-host/default

namePrefix: optimized-baseline-biren-vllm-

components:
  - ../../../../recipes/modelserver/components/images/biren-vllm/release

labels:
  - pairs:
      llm-d.ai/guide: optimized-baseline
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: biren
      llm-d.ai/model: Qwen72B_INT8
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-vllm.yaml
