alertmanager:
  enabled: false
grafana:
  enabled: false
defaultRules:
  create: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
  serviceMonitor:
    selfMonitor: false
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
prometheus:
  serviceMonitor:
    selfMonitor: false
  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v2.54.1
      sha: f6639335d34a77d9d9db382b92eeb7fc00934be8eae81dbc03b31cfe90411a94
    web:
      tlsConfig:
        cert:
          secret:
            name: prometheus-web-tls
            key: tls.crt
        keySecret:
          name: prometheus-web-tls
          key: tls.key
    replicas: 1
    retention: 1h
    retentionSize: 256MB
    walCompression: false
    scrapeInterval: 5s
    scrapeTimeout: 4s
    evaluationInterval: 5s
    maximumStartupDurationSeconds: 180
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
