apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vllm-p
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vllm-d
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
