{{- if and .Values.modelServers.enabled .Values.modelServers.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-d-stack.modelServerServiceAccountName" . }}
  labels:
{{ include "llm-d-stack.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.modelServers.serviceAccount.automountServiceAccountToken }}
{{- end }}
