latencyPredictor:
  enabled: true
  trainingServer:
    image:
      hub: us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension
      name: latency-training-server
      tag: main
      pullPolicy: Always
    port: 8000
    volumeSize: "20Gi"
    config:
      LATENCY_RETRAINING_INTERVAL_SEC: "10"
      LATENCY_MIN_SAMPLES_FOR_RETRAIN: "100"
      LATENCY_TTFT_MODEL_PATH: "/models/ttft.joblib"
      LATENCY_TPOT_MODEL_PATH: "/models/tpot.joblib"
      LATENCY_TTFT_SCALER_PATH: "/models/ttft_scaler.joblib"
      LATENCY_TPOT_SCALER_PATH: "/models/tpot_scaler.joblib"
      LATENCY_MODEL_TYPE: "xgboost"
      LATENCY_MAX_TRAINING_DATA_SIZE_PER_BUCKET: "500"
      LATENCY_OBJECTIVE_TYPE: "mean"

  predictionServers:
    count: 10
    startPort: 8001
    image:
      hub: us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension
      name: latency-prediction-server
      tag: main
      pullPolicy: Always
    volumeSize: "10Gi"
    config:
      LATENCY_MODEL_TYPE: "xgboost"
      PREDICT_HOST: "0.0.0.0"
      LOCAL_TTFT_MODEL_PATH: "/server_models/ttft.joblib"
      LOCAL_TPOT_MODEL_PATH: "/server_models/tpot.joblib"
      LOCAL_TTFT_SCALER_PATH: "/server_models/ttft_scaler.joblib"
      LOCAL_TPOT_SCALER_PATH: "/server_models/tpot_scaler.joblib"
      UVICORN_WORKERS: "28"
      OMP_NUM_THREADS: "1"
      MODEL_SYNC_INTERVAL_SEC: "30"
      LATENCY_OBJECTIVE_TYPE: "mean"

  eppEnv:
    LATENCY_MAX_SAMPLE_SIZE: "10000"
    LATENCY_MAX_CONCURRENT_DISPATCHES: "36"
    LATENCY_COALESCE_WINDOW_MS: "1"

inferenceExtension:
  replicas: 1
  flags:
  latencyPredictor:
    enabled: true
  image:
    name: llm-d-inference-scheduler
    hub: quay.io/rh_ee_rsaini
    tag: slo-pd-experimental
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "slo-prediction-plugins.yaml"
  pluginsCustomConfig:  # THIS CONFIG NEEDS TO BE CHECKED FOR INF SCHEDULER NEW IMAGE
    slo-prediction-plugins.yaml: |
      # ALWAYS DO PD IN THIS EXAMPLE (THRESHOLD 0)
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      featureGates:
      - prepareDataPlugins
      plugins:
      - type: prefix-cache-scorer
        parameters:
          maxPrefixBlocksToMatch: 256
          lruCapacityPerServer: 31250
      - type: predicted-latency-scorer
        parameters:
          sloBufferFactor: 1.0
          headroomSelectionStrategy: "least"
          samplingMean: 50
          maxSampledTokens: 10
      - type: max-score-picker
      schedulingProfiles:
      - name: default
        plugins:
        - pluginRef: prefix-cache-scorer
        - pluginRef: predicted-latency-scorer
        - pluginRef: max-score-picker

  # Distributed tracing configuration (OpenTelemetry)
  tracing:
    enabled: false
    # otelExporterEndpoint: "http://otel-collector:4317"
    # sampling:
    #   sampler: "parentbased_traceidratio"
    #   samplerArg: "0.1"
  # Monitoring configuration for EPP
  monitoring:
    interval: "10s"
    prometheus:
      enabled: true
      auth:
        secretName: pd-gateway-sa-metrics-reader-secret

inferencePool:
  targetPorts:
    - number: 8000
    - number: 8200
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inference-serving: "true"
      llm-d.ai/guide: "predicted-latency-based-scheduling"