apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../recipes/modelserver/base/single-host/default

namePrefix: optimized-baseline-metax-vllm-

components:
  - ../../../../recipes/modelserver/components/images/metax-vllm/release

labels:
  - pairs:
      llm-d.ai/guide: optimized-baseline
      llm-d.ai/model: Qwen3-14B
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: metax
    includeSelectors: true
    includeTemplates: true

patches:
  - path: patch-vllm.yaml
