apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../recipes/modelserver/base/single-host/pd/vllm
  - resource-claim-templates.yaml

namePrefix: pd-disaggregation-npu-vllm-

components:
  - ../../../../recipes/modelserver/components/images/npu-vllm/release
  - ../../../../recipes/modelserver/components/images/routing-sidecar/release

labels:
  - pairs:
      llm-d.ai/model: MiniMax-M2.7
      llm-d.ai/guide: pd-disaggregation
      llm-d.ai/accelerator-variant: npu
      llm-d.ai/accelerator-vendor: rebellions
      llm-d.ai/engine-type: vllm
    includeSelectors: true
    includeTemplates: true

patches:
  - path: patch-decode.yaml
  - path: patch-prefill.yaml
