inferenceExtension:
  replicas: 1
  image:
    # upstream GIE epp image does NOT support PD, have to use `llm-d-inference-scheduler`
    name: llm-d-inference-scheduler
    hub: ghcr.io/llm-d
    tag: v0.2.1
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "pd-config.yaml"
  pluginsCustomConfig:
    pd-config.yaml: |
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
      - type: prefill-header-handler
      - type: prefill-filter
      - type: decode-filter
      - type: max-score-picker
      - type: queue-scorer
      - type: prefix-cache-scorer
        parameters:
          hashBlockSize: 5               # MUST MATCH
          maxPrefixBlocksToMatch: 256
          lruCapacityPerServer: 31250
      - type: pd-profile-handler
        parameters:
          threshold: 32    # <-- need to figure out a good value, I am starting with 32
          hashBlockSize: 5                # MUST MATCH
      - type: kv-cache-scorer
      schedulingProfiles:
      - name: prefill
        plugins:
        - pluginRef: prefill-filter
        - pluginRef: prefix-cache-scorer
          weight: 2.0
        - pluginRef: kv-cache-scorer
          weight: 1.0
        - pluginRef: queue-scorer
          weight: 1.0
        - pluginRef: max-score-picker
      - name: decode
        plugins:
        - pluginRef: decode-filter
        - pluginRef: prefix-cache-scorer
          weight: 2.0
        - pluginRef: kv-cache-scorer
          weight: 1.0
        - pluginRef: queue-scorer
          weight: 1.0
        - pluginRef: max-score-picker
inferencePool:
  targetPortNumber: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
