apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../recipes/modelserver/base/single-host/pd-disaggregatedset/vllm

nameSuffix: -metax

components:
  - ../../../../../recipes/modelserver/components/images/metax-vllm/release
  - ../../../../../recipes/modelserver/components/images/routing-sidecar/nightly
  - ../../../../../recipes/modelserver/components/disaggregatedset-schema

labels:
  - pairs:
      llm-d.ai/model: Qwen3-32B
      llm-d.ai/guide: pd-disaggregation
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: metax
      llm-d.ai/engine-type: vllm
    fields:
      - path: spec/roles/spec/leaderWorkerTemplate/workerTemplate/metadata/labels
        kind: DisaggregatedSet
        create: true

patches:
  - path: patch-decode.yaml
  - path: patch-prefill.yaml
