apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: modelserver
          image: quay.io/ramalama/ramalama:latest
          command: ["llama-server"]
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
            - "--hf-repo"
            - "Qwen/Qwen2.5-0.5B-Instruct-GGUF"
            - "--hf-file"
            - "qwen2.5-0.5b-instruct-q4_k_m.gguf"
            - "--alias"
            - "Qwen3-32B"
            - "--ctx-size"
            - "2048"
            - "--temp"
            - "0.8"
            - "--cache-reuse"
            - "256"
            - "-ngl"
            - "999"
            - "--threads"
            - "4"
            - "--no-warmup"
            - "--log-colors"
            - "auto"
          env:
            - name: LLAMA_CACHE
              value: "/.cache/llama.cpp"
          securityContext:
            seccompProfile:
              type: Unconfined
            capabilities:
              add:
                - SYS_NICE
          resources:
            limits:
              memory: 4Gi
              cpu: "4"
              devic.es/dri: "1"
            requests:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - mountPath: /.cache
              name: torch-compile-cache
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: torch-compile-cache
          emptyDir: {}
