apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
components:
  - ../../../../../recipes/modelserver/components/disable-gke-nccl-tuner-patch

patches:
  - target:
      kind: LeaderWorkerSet
      name: wide-ep-llm-d-prefill
    patch: |-
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/affinity
        value:
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    llm-d.ai/role: prefill
                matchLabelKeys:
                - component
                topologyKey: cloud.google.com/gce-topology-block
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    llm-d.ai/role: prefill
                matchLabelKeys:
                - component
                topologyKey: cloud.google.com/gce-topology-subblock
  - target:
      kind: LeaderWorkerSet
      name: wide-ep-llm-d-decode
    patch: |-
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/affinity
        value:
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    llm-d.ai/role: decode
                matchLabelKeys:
                - component
                topologyKey: cloud.google.com/gce-topology-block
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    llm-d.ai/role: decode
                matchLabelKeys:
                - component
                topologyKey: cloud.google.com/gce-topology-subblock
  - target:
      kind: LeaderWorkerSet
    patch: |-
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/securityContext/privileged
        value: true
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/metadata/annotations
        value:
          networking.gke.io/default-interface: 'eth0'
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/-
        value:
          name: NVSHMEM_DISABLED_GDRCOPY
          value: "true"
      - op: replace
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/volumes/1
        value:
          name: hf-cache
          hostPath:
            path: /mnt/stateful_partition/kube-ephemeral-ssd/shared_disk/sglang-hf-cache/
            type: DirectoryOrCreate
      - op: replace
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/volumes/2
        value:
          name: sglang-cache
          hostPath:
            path: /mnt/stateful_partition/kube-ephemeral-ssd/shared_disk/sglang-cache/
            type: DirectoryOrCreate
